# Service to route traffic to via ingress
apiVersion: v1
kind: Service
metadata:
  name: {{ template "templ.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    service: {{ template "templ.name" . }}
