kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMapName | default "default-varnish" }}
data:
  default.vcl: |-
    {{- if and .Values.customVcl (ne .Values.customVcl "") }}
    {{- .Files.Get .Values.customVcl | nindent 4 }}
    {{- else }}
    {{- .Files.Get "templates/vcl/drupal_vcl_with_cache_tag_invalidation.vcl" | nindent 4 }}
    {{- end }}
